config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'codigos/activar'
  get 'codigos/home'
  post 'codigos/activate'
  scope :admin do
    resources :codigos
  end
  
  

  root 'codigos#home'

end

app/models/codigo.rb
class Codigo < ActiveRecord::Base
  belongs_to :user
  
  VALID_CODE = /([A-Z0-9])/
  validates :descripcion, format: {with: VALID_CODE}, presence: true, length: { maximum: 8, minimum:8},
            uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :codigos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/codigos_controller.rb
class CodigosController < ApplicationController
  before_action :set_codigo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:home]
  
  def new
    @codigo = Codigo.new
  end
  
  def create
    
    @codigo = Codigo.new(codigo_params)
    if @codigo.save
      redirect_to @codigo, notice: 'Código creado.'
    else
      render 'new'
    end
  end

  def index
    if !current_user.blank?
      @codigos = current_user.codigos
    else
      @codigos = Codigo.all
    end
  end

  def show
    
  end

  def destroy
    
    @codigo.destroy
     redirect_to codigos_url, notice: 'Codigo eliminado.'
  end

  def edit
  end
  
  def update
    if @codigo.update(codigo_params)
        redirect_to @codigo, notice: 'Codigo editado.'
    else
      render 'edit'
    end
  end
  
  def home
    @codigos = current_user.codigos
  end
  
  def activate
    codigo = Codigo.find_by(descripcion: params[:descripcion])
    if codigo.blank?
      redirect_to codigos_home_url, notice: 'Código Inválido'
    else
      codigo.update_attributes(user_id: current_user.id, estado: 'Activo')
      redirect_to root_url, notice: 'Código activado.'
    end
  end
  
  def activar
    
  end

 
  
  private
    def codigo_params
      params.require(:codigo).permit(:descripcion, :estado)
    end
    
    def set_codigo
      @codigo = Codigo.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codigos_helper.rb
module CodigosHelper
end

app/views/codigos/activar.html.erb
<%= form_tag('activate') do%>
  <%= text_field_tag 'descripcion' %>
  <%= submit_tag 'Activar' %>
<% end %>

app/views/codigos/edit.html.erb
<%= form_for(@codigo) do |f| %>
  <% if @codigo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@codigo.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @codigo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :descripcion %>
  <%= f.text_field :descripcion %>
  <br/>
  
  <%= f.submit 'Guardar' %>
  
<% end %>

app/views/codigos/home.html.erb
<h1>Tus Codigos:</h1>


  <table class="table">
    <% @codigos.each do |codigo| %>
      <tr>
        <td> <%= codigo.descripcion %></td>
        <td> <%= codigo.estado %></td>
      </tr>
    <% end %>
  </table>
  
<%= link_to 'Agregar código', codigos_activar_path %>

app/views/codigos/index.html.erb
<h1>Codigos:</h1>


  <table class="table">
  <%if !@codigos.blank? %>
    <% @codigos.each do |codigo| %>
      <tr>
        <td> <%= codigo.descripcion %></td>
        <td> <%= codigo.estado %></td>
        <td> <%= link_to 'Ver', codigo_path(codigo.id)%></td>
        <td> <%= link_to 'Eliminar', codigo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
  </table>
  
<%= link_to 'Agregar código', new_codigo_path %>

app/views/codigos/new.html.erb
<%= form_for(@codigo) do |f| %>
  <% if @codigo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@codigo.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @codigo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :descripcion %>
  <%= f.text_field :descripcion %>
  <br/>
  
  <%= f.submit 'Crear' %>
  
<% end %>

app/views/codigos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @codigo.descripcion %>
</p>

<%= link_to 'Edit', edit_codigo_path(@codigo) %> |
<%= link_to 'Back', codigos_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PruebaHpp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="badge">Logged in as <strong><%= current_user.email %></strong></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |</li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
        
      </ul>
    </nav>
    
  </div>
  
</header>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
  <%= yield %>  
</div>


</body>
</html>